name: CI_ARC

on:
  push:
  pull_request:


jobs:
  crosstool:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [ "ubuntu-latest" ]
    steps:
      - name: "clone"
        uses: actions/checkout@v2
      - name: "prereq Linux"
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install -y gperf help2man libtool-bin
      - name: "build ct-ng"
        run: |
          ./bootstrap
          ./configure --prefix=$PWD/.local/
          make
          make install
          tar -cf ct-ng.tar .local/
      - name: "upload ct-ng"
        uses: actions/upload-artifact@v2
        with:
          name: crosstool.${{ matrix.host }}
          path: ct-ng.tar
      - name: "upload config.log"
        uses: actions/upload-artifact@v2
        with:
          name: config.log.${{ matrix.host }}
          path: config.log
        if: ${{ always() }}

  # tarballs:
  #   needs: crosstool
  #   runs-on: ${{ matrix.host }}
  #   strategy:
  #     matrix:
  #       host: [ "ubuntu-latest" ]
  #   steps:
  #     - name: "download ct-ng"
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: crosstool.${{ matrix.host }}
  #     - name: "extract ct-ng"
  #       run: |
  #         tar -xf ct-ng.tar
  #     - name: "prereq Linux"
  #       if: ${{ runner.os == 'Linux' }}
  #       run: |
  #         sudo apt-get install -y gperf help2man libtool-bin
  #         echo "$GITHUB_WORKSPACE/.local/bin" >> $GITHUB_PATH

  toolchains:
    #needs: [ crosstool, tarballs ]
    needs: [ crosstool ]
    uses: ./.github/workflows/build-toolchains-arc.yml
    with:
      samples: >-
        [
          "snps-arc-arc700-linux-uclibc",
          "snps-arc-archs-linux-gnu",
          "snps-arc-archs-linux-uclibc",
          "snps-arc-archs-native-gnu",
          "snps-arc-elf32-macos",
          "snps-arc-elf32-win",
          "snps-arc-multilib-elf32",
          "snps-arc64-snps-linux-gnu",
          "snps-arc64-snps-native-gnu",
          "snps-arc64-unknown-elf"
        ]
